services:
 
  core_microservice:
    build:
      context: .
      dockerfile: apps/core_microservice/Dockerfile
    environment:
      CORE_HTTP_PORT: 3001
      SWAGGER_PATH: api/docs
    ports:
      - "3001:3001"
