global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'innogram-core'
    metrics_path: /monitoring/prometheus
    static_configs:
      - targets: ['core:3001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
