#!/bin/sh
set -eu

export NGINX_CLIENT_UPSTREAM="${NGINX_CLIENT_UPSTREAM:-client:3000}"
export NGINX_GATEWAY_UPSTREAM="${NGINX_GATEWAY_UPSTREAM:-gateway:3004}"
export NGINX_CORE_UPSTREAM="${NGINX_CORE_UPSTREAM:-core:3001}"
export NGINX_AUTH_UPSTREAM="${NGINX_AUTH_UPSTREAM:-auth:3002}"
export NGINX_MINIO_UPSTREAM="${NGINX_MINIO_UPSTREAM:-minio:9000}"
export NGINX_SERVER_NAME="${NGINX_SERVER_NAME:-localhost}"
export MINIO_BUCKET="${MINIO_BUCKET:-main}"

envsubst '${NGINX_CLIENT_UPSTREAM} ${NGINX_GATEWAY_UPSTREAM} ${NGINX_CORE_UPSTREAM} ${NGINX_AUTH_UPSTREAM} ${NGINX_MINIO_UPSTREAM} ${NGINX_SERVER_NAME} ${MINIO_BUCKET}' \
  < /etc/nginx/templates/default.conf.template \
  > /etc/nginx/conf.d/default.conf

exec nginx -g 'daemon off;'
