apiVersion: v1
kind: Secret
metadata:
  name: innogram-secrets
  namespace: innogram
  labels:
    app.kubernetes.io/part-of: innogram
type: Opaque
stringData:
  POSTGRES_USER: '${POSTGRES_USER}'
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY}'
  MINIO_SECRET_KEY: '${MINIO_SECRET_KEY}'
  MINIO_USER: '${MINIO_USER}'
  MINIO_PASSWORD: '${MINIO_PASSWORD}'
  AUTH_JWT_ACCESS_TOKEN_KEY_ID: '${AUTH_JWT_ACCESS_TOKEN_KEY_ID}'
  AUTH_JWT_ACCESS_TOKEN_PRIVATE_KEY: '${AUTH_JWT_ACCESS_TOKEN_PRIVATE_KEY}'
  AUTH_JWT_REFRESH_TOKEN_SECRET: '${AUTH_JWT_REFRESH_TOKEN_SECRET}'
  AUTH_GOOGLE_CLIENT_ID: '${AUTH_GOOGLE_CLIENT_ID}'
  AUTH_GOOGLE_CLIENT_SECRET: '${AUTH_GOOGLE_CLIENT_SECRET}'
  AUTH_ALLOWED_OAUTH_REDIRECT_ORIGINS: 'http://localhost'
