apiVersion: v1
kind: Secret
metadata:
  name: innogram-secrets
  namespace: innogram
  labels:
    app.kubernetes.io/part-of: innogram
type: Opaque
stringData:
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  MINIO_ACCESS_KEY: 'minioadmin'
  MINIO_SECRET_KEY: 'minioadmin'
  MINIO_USER: 'minioadmin'
  MINIO_PASSWORD: 'minioadmin'
  AUTH_JWT_ACCESS_TOKEN_KEY_ID: 'k8s-dev-key-1'
  AUTH_JWT_ACCESS_TOKEN_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCUJd5c6ta2jWe6\n3ZRXW6FvH0jj0n7IcH/SxznRttDydc68dvlTZlmNXsyesav+rBOjbeufWH88j+pw\n9iUUGNCgC0DRmj2yUszIpwZ2YBWXvascv9bQFm2dqHqMwz0Frb7da6HcC/dWFf2L\nciuV9cr9z+2T/5Npi9HMF7mSqhvfZqvgRPU/UDQVNdNqoKEDopgaW/gpnOWinsTA\nKqIvj67SKHMvgXX8P76QVe+z9V2DpKO39Sml0pO/9YofWzXh11I4TjWPr50ZRkNb\nOjgpuz6RVn/PVEGy6oUVAWVqCzGZhgud4Dc9qBp8NuncIp1pt0Aeia2nhtMyC5bj\nt2OuSXLxAgMBAAECggEAH5q4hj//EDC4aU/t3nkIxmj5Jsj4DRCa5D9mIUwL5T2m\nneQPqnASOKt5oX0rwQe6pMnFU1gQxL26+OA55sCoeQwNhumNseYiE8g2A7jZwmZP\nA7IVRI0UU2bmxfK8qOJ47kmQ3R2cZTwJu97eV355EI50E3eZXhHa7tw81YH+sjik\nzaiwA2obreNC+TFv2f2N4jtueWQUi8vBK6FRpQP0cz2ZGl05nItjFvhZESkV3ewi\n/W4EoZ2Efvwvtbr7PK4lCurktYj/huXWwnRvziGhDYPNN+yJnjNXWt8NZkGrED1+\nai4HOB89dAc6FN64TKFJD+p0thOr3Pg/fLKnceioJQKBgQDMz5ipidTFx7r1cm9J\nsJQJnYd0ZbgF8MvipkefxorX0isi6X3CwcEDCKd4QyBfDOUSL2z4L6NAfbQ96h2t\nOpwz+5nL3h189Ppi+5j1HaJkA8yO48bU0+RZk1RwZ0L/VG1dvhrdvKpdA8O18Pra\nBiuiSF5WCuDuKP0Yp5o5aiY2kwKBgQC5LM6wYOdHQ71kUvgQmelMAYCxvwzGD+Xf\nM3UoyHX9mFUf7y4EKlhcPDvljRnJSjLaeOUG0rSWZPpLftFft46VLnEljVudJmCJ\nfAtZOrCESgfLY3RZIx8wuJ4/rPo7uEcoYLSuAR6+WDFRw1VfKzFsoebGp92KpIeS\nj39mDuN+6wKBgHshMz55xplBAn0dVxqONfGx6wVnQcMQiQKxxM2hp0co6xYKGblE\nkq0oPsZmVMfQEMdmC7UJrrPO3tV6Mm06lz4JPOT7m+7LuNxZNhPmxQIr5obhGWBK\nIzZXBKSu7/Bg6X86ExzLmABjiv2O6sC4hPMDXvOLhr6nlcGEwYtS7bZRAoGALD0p\nL/gmqN7lG1e7DfRHSTI+tbhH6/WWXGmlvtWNYsWG6Lcyjiozq+1z/dZk57MDTTB+\nvs+N9zQum+SzTqPCu585xtfroDKv84igCXQ9AY3SKOQcwsLiS7h/jgTcT3IqBdp8\nr+lyl9ToC3mYJsFh8GsJgEJQajP+c6Q2soIyFXsCgYAWGSCjqb5CElzFybC32nHU\nCSBNMx62DOw9nKl3w20DcD2UHTBFL2dgNHz0dNid/f7yksYb3DI4q5Ux8+hD3La3\nd5S9OPvTw0hquK7pc0e7WneLzRqSQTaPxU3j+xrPhS/TqM6oHrOb2voFcEbgkxgW\nEjhIGH3IZFFg7AIey6aiug==\n-----END PRIVATE KEY-----"
  AUTH_JWT_REFRESH_TOKEN_SECRET: 'CHANGE_ME_IN_PRODUCTION'
  AUTH_GOOGLE_CLIENT_ID: 'YOUR_GOOGLE_CLIENT_ID'
  AUTH_GOOGLE_CLIENT_SECRET: 'YOUR_GOOGLE_CLIENT_SECRET'
  AUTH_ALLOWED_OAUTH_REDIRECT_ORIGINS: 'http://localhost'
