import type { Metadata } from 'next';
import './global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="layout">
        <header>Header</header>
        <main className="layout__main">{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
