import type { Metadata } from 'next';
import './global.scss';
import { AppErrorBoundary } from './widgets/app-error-boundary';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="layout">
        <AppErrorBoundary>
          <header>Header</header>
          <main className="layout__main">{children}</main>
          <footer>Footer</footer>
        </AppErrorBoundary>
      </body>
    </html>
  );
}
